---

disableHugoGeneratorInject: true

disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
  - sitemap

defaultContentLanguage: en
languages:
  uk:
    languageName: Українська
  en:
    languageName: English


